name: Release

on:
  push:
    branches:
      - master
    
    tags:
      - v*

env:
  CTAN_URL: https://mirrors.rit.edu/CTAN
  TL_PACKAGES: amscls amsmath anyfontsize blkarray booktabs boondox braket caption ctex endnotes fancyhdr fandol float graphics hyperref latexmk libertinus-fonts luatex85 l3packages mathalpha mathtools metafont needspace newfloat pgfplots psnfss scalerel siunitx stackengine threeparttable times tools ulem wasysym xcolor xecjk multirow enumitem collection-fontsrecommended collection-fontsextra

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      SET_PATH: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install TeX Live
        run: |
          ${{ env.SET_PATH }}
          wget ${{ env.CTAN_URL }}/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
          tlmgr install ${{ env.TL_PACKAGES }}
          tlmgr update --self --all --no-auto-install --repository=${{ env.CTAN_URL }}/systems/texlive/tlnet/
      - name: Compile test file
        run: |
          ${{ env.SET_PATH }}
          #cd test
          latexmk -xelatex  -halt-on-error -shell-escape main
          mv main.pdf szabo_zh-$VERSION.pdf
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            szabo_zh-v*.pdf
